name: HENCK
favicon: null
layout_spectrum: 0.73553
typography_spectrum: 0.59657
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#57638d'
    - '#0f0e09'
    - '#cceeb1'
    - '#959698'
    - '#9a3929'
  brandStrength: 0.43378266459330916
  lightness: 0.20091791823506355
  saturation: 0.5712839835323393
  rhythmicContrast: 0.1219616150483489
purpose: []
